name: Build DB

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_db:
    name: Build, Test, and Release DB
    runs-on: ubuntu-20.04
    env:
      DB_DATABASE: dol
      DB_USER: root
      DB_PASSWORD: 'root'
      DB_HOST: localhost
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Setup Build Environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - name: Install necessary packages
        run: sudo apt install -y --no-install-recommends sqlite3
      - name: Generate Release Info
        run: |
          last_build_number=$(git tag -l --sort=creatordate | grep -E '^[0-9]+$' | tail -n1);
          
          if [ -n "$last_build_number" ]; \
          then git log origin/master --first-parent  --format="%s%n%w(0,4,4)%b" "$last_build_number".. | grep -v "^$" > patch_notes.txt; \
          sed -i '1s/^/```\n/' patch_notes.txt; \
          new_build_number=$((1+$last_build_number)); \
          else new_build_number=1; printf '```\nInitial Release' > patch_notes.txt; \
          fi;
          echo "new_build_number=$new_build_number" >> $GITHUB_ENV
      - name: Build Queries
        run: |
          cp config/config.example.yml config/config.yml
          go run concat.go
          mv public-db.sql public-db.mysql.sql
          go run concat.go -sqlite
          mv public-db.sql public-db.sqlite.sql
      - name: Test SQLite
        run: sqlite3 test.db < public-db.sqlite.sql
      - name: Test MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE dol;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
          cat public-db.sql | mysql -h 127.0.0.1 -u root -P 3306 --password=root -D dol
      - name: Compress Queries
        if: ${{ github.event_name == 'push' }}
        run: |
          mkdir build_artifacts
          zip -Z bzip2 public-db.mysql.zip public-db.mysql.sql
          zip -Z bzip2 public-db.sqlite.zip public-db.sqlite.sql
          mv public-db.mysql.zip public-db.sqlite.zip build_artifacts
      - name: Create Release
        if: ${{ github.event_name == 'push' }}
        run: |
          gh release create "${{ env.new_build_number }}" --title "Public-DB Release ${{ env.new_build_number }}" -F patch_notes.txt build_artifacts/*
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
